### ISSUE TITLE
Trading multiple coins on bitfinex is not possible due to ERR_RATE_LIMIT exceptions

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#174]
Using catalyst: 0.4.7

I have an algo that trades 14 pairs (for testing, ideally it would be much more).  On the first call to handle_data I get `data.can_trade(symbols)` and `data.current(symbols, 'close')` where `symbols` is a list of 14 asset pairs.  This results in the following errors:
```
WARNING: CCXT: unable to fetch ticker bitfinex / eos_usd: bitfinex GET https://api.bitfinex.com/v1/pubticker/EOSUSD request timeout
WARNING: CCXT: unable to fetch ticker bitfinex / rrt_usd: bitfinex ERR_RATE_LIMIT
WARNING: CCXT: unable to fetch ticker bitfinex / neo_usd: bitfinex ERR_RATE_LIMIT
```
Sometimes there are more, sometimes less coins that fail.  But after about 5 attempts it never got the data for all 14 pairs.

The following Exception follows shortly after when trying to get the history of those symbols:
```
DDoSProtection                            Traceback (most recent call last)
...
/home/guido/anaconda3/envs/catalyst/lib/python2.7/site-packages/ccxt/base/exchange.pyc in raise_error(self, exception_type, url, method, error, details)
    279                 method,
    280                 url,
--> 281                 details,
    282             ]))
    283         else:

DDoSProtection: bitfinex GET https://api.bitfinex.com/v2/candles/trade:1m:tXRPUSD/hist?sort=1&start=1516507680000&limit=15 429 Client Error: Too Many Requests for url: https://api.bitfinex.com/v2/candles/trade:1m:tXRPUSD/hist?sort=1&start=1516507680000&limit=15 ["error", 11010, "ratelimit: error"]
```

Note: if I limit my algo to 5 coins it appears to avoid this issue but this is not ideal.  I do get the following warning though: 
```
INFO: exchange_algorithm: portfolio balances, cash: <xxx>, positions: <yyy>
WARNING: exchange_algorithm: unable to calculate performance: 'starting_cash'
```
but it does not crash the algo.

**Comment by fredfortier** [comment]
Yes, we’ll fix this in the next version. We had some issues with the
‘fetch_tickers()’ method so we resorted to a loop of ‘fetch_ticker()’
temporarily.

**Comment by fredfortier** [comment]
Confirmed that the underlying issue is fixed and implemented `fetch_tickers()` again. As a result, when possible (like with Bitfinex), tickers will be fetched using one request instead of multiple.

**Comment by gatapia** [comment]
Just checked this again in 0.4.7 and still happens, currently I am limited to trading 5 coins, any more and I get this error.  Any timeline for this (for bitfinex)?

**Comment by fredfortier** [comment]
Yes, this change is in our develop branch but not release yet. Coming up on
Monday.

**Comment by fredfortier** [comment]
In release 0.5.2

**Comment by gatapia** [comment]
This is still happening in 0.5.3.

I have 14 coins and on the initial frame where I get history for all 14 coins at once I get the following:
```
2018-02-10 01:53:13.614737] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-02-10 01:53:16.618776] INFO: run_algo: running algo in paper-trading mode
002200_models: running paper trading on bitfinex with $2500 - stats ~/.catalyst/data/live_algos/002200_models
[2018-02-10 01:53:17.208386] INFO: exchange_algorithm: portfolio balances, cash: 2500.0, positions: 0.0
[2018-02-10 01:53:52.733847] WARNING: CCXT: unable to fetch ticker bitfinex / XMR/USD: bitfinex {"error":"ERR_RATE_LIMIT"}
[2018-02-10 01:53:52.736912] WARNING: DataPortalExchange: fetching spot value again.
[2018-02-10 01:53:57.781595] WARNING: CCXT: unable to fetch ticker bitfinex / XMR/USD: bitfinex {"error":"ERR_RATE_LIMIT"}
[2018-02-10 01:53:57.782659] WARNING: DataPortalExchange: fetching spot value again.
[2018-02-10 01:54:05.323684] WARNING: CCXT: unable to fetch ticker bitfinex / XMR/USD: bitfinex {"error":"ERR_RATE_LIMIT"}
[2018-02-10 01:54:05.325061] WARNING: DataPortalExchange: fetching spot value again.
[2018-02-10 01:54:15.615437] WARNING: CCXT: unable to fetch ticker bitfinex / XMR/USD: bitfinex {"error":"ERR_RATE_LIMIT"}
[2018-02-10 01:54:15.616608] WARNING: DataPortalExchange: fetching spot value again.
[2018-02-10 01:54:25.754150] INFO: exchange_algorithm: Interruption signal detected 2, exiting the algorithm
[2018-02-10 01:54:25.754856] INFO: exchange_algorithm: Exiting the algorithm. Calling `analyze()` before exiting the algorithm.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-9cfe86a7f819> in <module>()
      1 settings = Algorithm002000Settings(namespace=namespace, coins=coins, detailed_analysis=False)
----> 2 Algorithm002000(ensemble, scalers, settings).paper_trade(2500.0)

~/dev/projects/catalyst/src/utils/algorithm.py in paper_trade(self, capital_base, exchange_name)
    294             live=True,
    295             data_frequency='minute',
--> 296             simulate_orders=True)
    297 
    298     def live_trade(self, capital_base, exchange_name='bitfinex'):

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/run_algo.py in run_algorithm(initialize, capital_base, start, end, handle_data, before_trading_start, analyze, data_frequency, data, bundle, bundle_timestamp, default_extension, extensions, strict_extensions, environ, live, exchange_name, base_currency, algo_namespace, live_graph, analyze_live, simulate_orders, auth_aliases, stats_output, output)
    547         simulate_orders=simulate_orders,
    548         auth_aliases=auth_aliases,
--> 549         stats_output=stats_output
    550     )

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/run_algo.py in _run(handle_data, initialize, before_trading_start, analyze, algofile, algotext, defines, data_frequency, capital_base, data, bundle, bundle_timestamp, start, end, output, print_algo, local_namespace, environ, live, exchange, algo_namespace, base_currency, live_graph, analyze_live, simulate_orders, auth_aliases, stats_output)
    329     ).run(
    330         data,
--> 331         overwrite_sim_params=False,
    332     )
    333 

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py in run(self, data, overwrite_sim_params)
    307         data.attempts = self.attempts
    308         return super(ExchangeTradingAlgorithmBase, self).run(
--> 309             data, overwrite_sim_params
    310         )
    311 

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/algorithm.py in run(self, data, overwrite_sim_params)
    722         try:
    723             perfs = []
--> 724             for perf in self.get_generator():
    725                 perfs.append(perf)
    726 

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py in transform(self)
    222             for dt, action in self.clock:
    223                 if action == BAR:
--> 224                     for capital_change_packet in every_bar(dt):
    225                         yield capital_change_packet
    226                 elif action == SESSION_START:

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py in every_bar(dt_to_use, current_data, handle_data)
    135                     perf_tracker.process_commission(commission)
    136 
--> 137             handle_data(algo, current_data, dt_to_use)
    138 
    139             # grab any new orders from the blotter, then clear the list.

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/events.py in handle_data(self, context, data, dt)
    214                     context,
    215                     data,
--> 216                     dt,
    217                 )
    218 

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/events.py in handle_data(self, context, data, dt)
    233         """
    234         if self.rule.should_trigger(dt):
--> 235             self.callback(context, data)
    236 
    237 

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py in handle_data(self, data)
    759         )
    760         if self._handle_data:
--> 761             self._handle_data(self, data)
    762 
    763         # Unlike trading controls which remain constant unless placing an

~/dev/projects/catalyst/src/utils/algorithm.py in <lambda>(ctx, data)
    286         run_algorithm(
    287             initialize=lambda ctx: self.initialize(ctx, None, 'paper_trading'),
--> 288             handle_data=lambda ctx, data: self.handle_data_wrapper(ctx, data),
    289             analyze=lambda ctx, data: analyze_results(self.opts, data),
    290             exchange_name=exchange_name,

~/dev/projects/catalyst/src/utils/algorithm.py in handle_data_wrapper(self, context, data)
    249                 self.log.info('starting day: %s cash: %.0f portfolio: %.0f' % (data.current_dt, context.portfolio.cash, context.portfolio.portfolio_value))
    250 
--> 251             coins_data = self.get_all_coins_data(context, data)
    252 
    253             self.next_period(context, data, coins_data);

~/dev/projects/catalyst/src/utils/algorithm.py in get_all_coins_data(self, context, data)
    166         available = [(coin, sym) for (coin, sym, can_trade) in zip(self.opts.coins, self.symbols, can_trades) if can_trade]
    167         available_symbols = [sym for (coin, sym) in available]
--> 168         close_prices = data.current(available_symbols, 'close')
    169 
    170         cache_keys = [coin + str(data.current_dt) for coin in self.opts.coins]

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/_protocol.pyx in catalyst._protocol.check_parameters.__call__.assert_keywords_and_call()

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/_protocol.pyx in catalyst._protocol.BarData.current()

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py in get_spot_value(self, assets, field, dt, data_frequency)
    158             retry_exceptions=(ExchangeRequestError,),
    159             cleanup=lambda: log.warn('fetching spot value again.'),
--> 160             args=(assets, field, dt, data_frequency))
    161 
    162     @abc.abstractmethod

~/dev/tools/miniconda3/lib/python3.6/site-packages/redo/__init__.py in retry(action, attempts, sleeptime, max_sleeptime, sleepscale, jitter, retry_exceptions, cleanup, args, kwargs)
    156     for _ in retrier(attempts=attempts, sleeptime=sleeptime,
    157                      max_sleeptime=max_sleeptime, sleepscale=sleepscale,
--> 158                      jitter=jitter):
    159         try:
    160             logfn = log.info if n != 1 else log.debug

~/dev/tools/miniconda3/lib/python3.6/site-packages/redo/__init__.py in retrier(attempts, sleeptime, max_sleeptime, sleepscale, jitter)
     83         if _ < attempts - 1:
     84             log.debug("sleeping for %.2fs (attempt %i/%i)", sleeptime_real, _ + 1, attempts)
---> 85             time.sleep(sleeptime_real)
     86 
     87 

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py in signal_handler(self, signal, frame)
    437         log.info('Interruption signal detected {}, exiting the '
    438                  'algorithm'.format(signal))
--> 439         self.interrupt_algorithm()
    440 
    441     @property

~/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py in interrupt_algorithm(self)
    404             algo_folder = get_algo_folder(self.algo_namespace)
    405             folder = join(algo_folder, 'daily_performance')
--> 406             files = [f for f in listdir(folder) if isfile(join(folder, f))]
    407 
    408             daily_perf_list = []

FileNotFoundError: [Errno 2] No such file or directory: '.../.catalyst/data/live_algos/model/daily_performance'
```

**Comment by gatapia** [comment]
Will this issue be reopened or should I open a new one regarding this `WARNING: CCXT: unable to fetch ticker bitfinex / <pair>: bitfinex {"error":"ERR_RATE_LIMIT"}` error that prevents any more than 8 or so coins from being traded at once on bitfinex.

Note currently I am using `data.current(symbols, 'close')` and `data.history(symbols, ['close', 'volume'], ...)` to get all prices at once is there a better practice for this to try to mitigate this issue.

**Comment by salihkilic** [comment]
I'm having the same issue. Using a list of assets with data.history() always returns an error, either a time-out or an explicit reference to the rate limit.

**Comment by garofas** [comment]
Somebody managed to solve this issue?
