### ISSUE TITLE
live=True data.history(bar_count=1) Exception

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#236]
When working in live mode (simulate_orders=True, have not tested False). And running `data.history(multiple_symbols, ['close', 'volume'], bar_count=1, frequency='5T')`.  Throws an error _sometimes_.

Solution is to just get `<number_of_required_bars> + 1` and then doing a tail(<number_of_required_bars>) as the number of bars returned is inconsistent.

When bar_count=1 the following exception can occur:
```
Traceback (most recent call last):
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/guido/dev/projects/catalyst/src/algo/reproduce_bug.py", line 39, in <module>
    simulate_orders=True)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 549, in run_algorithm
    stats_output=stats_output
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 331, in _run
    overwrite_sim_params=False,
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 309, in run
    data, overwrite_sim_params
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 761, in handle_data
    self._handle_data(self, data)
  File "/home/guido/dev/projects/catalyst/src/algo/reproduce_bug.py", line 25, in _handle_data
    frequency='5T')
  File "catalyst/_protocol.pyx", line 120, in catalyst._protocol.check_parameters.__call__.assert_keywords_and_call
  File "catalyst/_protocol.pyx", line 708, in catalyst._protocol.BarData.history
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 95, in get_history_window
    ffill))
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/redo/__init__.py", line 162, in retry
    return action(*args, **kwargs)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 69, in _get_history_window
    ffill)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 218, in get_exchange_history_window
    False)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange.py", line 517, in get_history_window
    first_candle = candles[asset][0]
IndexError: list index out of range
```

With bar_count = 2 I get a pandas panel that can sometimes be 3 rows long (about 1 in 5 times).

This was tested on bitfinex and polo with the following code:

```
from catalyst.api import symbol
from catalyst.utils.run_algo import run_algorithm

coins = ['bch', 'btc', 'dash', 'etc', 'eth', 'ltc', 'nxt', 'rep', 'str', 'xmr', 'xrp', 'zec']
symbols = None

def _handle_data(context, data):
    global symbols
    if symbols is None: symbols = [symbol(c + '_usdt') for c in coins]

    print('getting history for:', [s.symbol for s in symbols])
    history = data.history(symbols,
                    ['close', 'volume'],
                    bar_count=1, # EXCEPTION, Change to 2
                    frequency='5T')
    print('history: ', history.shape)

run_algorithm(
            initialize=lambda ctx: print('init'),
            handle_data=_handle_data,
            analyze=lambda _, results: True,
            exchange_name='poloniex',
            base_currency='usdt',
            algo_namespace='reproduce_polo_bug',
            live=True,
            data_frequency='minute',
            capital_base=3000,
            simulate_orders=True)
```

**Comment by gatapia** [comment]
I was wrong, even with a + 1 to the `bar_count` this can still happen.  The following code (note the `bar_count=2 `) crashed eventually (took longer):
```
from catalyst.api import symbol
from catalyst.utils.run_algo import run_algorithm

coins = ['bch', 'btc', 'dash', 'etc', 'eth', 'ltc', 'nxt', 'rep', 'str', 'xmr', 'xrp', 'zec']
symbols = None

def _handle_data(context, data):
    global symbols
    if symbols is None: symbols = [symbol(c + '_usdt') for c in coins]

    print('getting history for:', [s.symbol for s in symbols])
    history = data.history(symbols,
                    ['close', 'volume'],
                    bar_count=2,
                    frequency='5T')
    print('history: ', history.shape)

run_algorithm(
            initialize=lambda ctx: print('init'),
            handle_data=_handle_data,
            analyze=lambda _, results: True,
            exchange_name='poloniex',
            base_currency='usdt',
            algo_namespace='reproduce_polo_bug',
            live=True,
            data_frequency='minute',
            capital_base=3000,
            simulate_orders=True)
```

Exception (same):
```
[2018-02-17 02:16:33.003546] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-02-17 02:16:36.007036] INFO: run_algo: running algo in paper-trading mode
[2018-02-17 02:16:36.350743] INFO: exchange_bundle: pricing data for ['btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2018-02-15 00:00:00+00:00, updating the bundles.
    [====================================]  Ingesting daily price data for btc_usd on bitfinex:  100%
init
[2018-02-17 02:16:38.341748] INFO: exchange_algorithm: portfolio balances, cash: 3000.0, positions: 0.0
getting history for: ['bch_usdt', 'btc_usdt', 'dash_usdt', 'etc_usdt', 'eth_usdt', 'ltc_usdt', 'nxt_usdt', 'rep_usdt', 'str_usdt', 'xmr_usdt', 'xrp_usdt', 'zec_usdt']
history:  (2, 2, 12)
[2018-02-17 02:17:03.601224] INFO: exchange_algorithm: statistics for the last 1 minutes:
                           starting_cash  ending_cash  portfolio_value  pnl  long_exposure  short_exposure  orders  transactions
period_close
2018-02-17 02:17:00+00:00           3000       3000.0           3000.0  0.0              0               0       0             0
[2018-02-17 02:17:03.608609] INFO: exchange_algorithm: portfolio balances, cash: 3000.0, positions: 0.0
getting history for: ['bch_usdt', 'btc_usdt', 'dash_usdt', 'etc_usdt', 'eth_usdt', 'ltc_usdt', 'nxt_usdt', 'rep_usdt', 'str_usdt', 'xmr_usdt', 'xrp_usdt', 'zec_usdt']
history:  (2, 2, 12)
[2018-02-17 02:17:27.634212] INFO: exchange_algorithm: statistics for the last 1 minutes:
                           starting_cash  ending_cash  portfolio_value  pnl  long_exposure  short_exposure  orders  transactions

...

[2018-02-17 02:40:00.246176] INFO: exchange_algorithm: portfolio balances, cash: 3000.0, positions: 0.0
getting history for: ['bch_usdt', 'btc_usdt', 'dash_usdt', 'etc_usdt', 'eth_usdt', 'ltc_usdt', 'nxt_usdt', 'rep_usdt', 'str_usdt', 'xmr_usdt', 'xrp_usdt', 'zec_usdt']
history:  (2, 3, 12)
[2018-02-17 02:40:23.506260] INFO: exchange_algorithm: statistics for the last 1 minutes:
                           starting_cash  ending_cash  portfolio_value  pnl  long_exposure  short_exposure  orders  transactions
period_close
2018-02-17 02:41:00+00:00           3000       3000.0           3000.0  0.0              0               0       0             0
[2018-02-17 02:41:00.586104] INFO: exchange_algorithm: portfolio balances, cash: 3000.0, positions: 0.0
getting history for: ['bch_usdt', 'btc_usdt', 'dash_usdt', 'etc_usdt', 'eth_usdt', 'ltc_usdt', 'nxt_usdt', 'rep_usdt', 'str_usdt', 'xmr_usdt', 'xrp_usdt', 'zec_usdt']
Traceback (most recent call last):
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/guido/dev/projects/catalyst/src/algo/reproduce_bug.py", line 28, in <module>
    simulate_orders=True)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 549, in run_algorithm
    stats_output=stats_output
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 331, in _run
    overwrite_sim_params=False,
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 309, in run
    data, overwrite_sim_params
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/events.py", line 216, in handle_data
    dt,
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/utils/events.py", line 235, in handle_data
    self.callback(context, data)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 761, in handle_data
    self._handle_data(self, data)
  File "/home/guido/dev/projects/catalyst/src/algo/reproduce_bug.py", line 15, in _handle_data
    frequency='5T')
  File "catalyst/_protocol.pyx", line 120, in catalyst._protocol.check_parameters.__call__.assert_keywords_and_call
  File "catalyst/_protocol.pyx", line 708, in catalyst._protocol.BarData.history
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 95, in get_history_window
    ffill))
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/redo/__init__.py", line 162, in retry
    return action(*args, **kwargs)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 69, in _get_history_window
    ffill)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange_data_portal.py", line 218, in get_exchange_history_window
    False)
  File "/home/guido/dev/tools/miniconda3/lib/python3.6/site-packages/catalyst/exchange/exchange.py", line 517, in get_history_window
    first_candle = candles[asset][0]
IndexError: list index out of range
```

**Comment by lenak25** [comment]
Hi @gatapia , thanks for reporting. 
I was able to reconstruct using both 1 and 2 bars.
Will investigate to understand the root cause.
Thanks.

**Comment by lenak25** [comment]
It seems that Poloniex sometimes returns empty candle list. It happens more frequently in less traded coins (like DASH). 
Will work on a solution.

**Comment by gatapia** [comment]
Note: Also happens w/ Bitfinex so its not exchange specific

**Comment by lenak25** [comment]
Sure, thanks for the reminder. In any case, we are working on a generic solution.

**Comment by lenak25** [comment]
@gatapia , thanks again for reporting this issue.
A fix was pushed to develop branch.

**Comment by gatapia** [comment]
@lenak25 I will leave my paper-trade algo running for a while to see if the empty candles issue is resolved (looks ok after 10 mins now).  

However the problem that `bar_count=1` can return 2 candles still exists.

My code above can be used to reproduce. i.e. `print('history: ', history.shape)` should print out 1 row when `bar_count = 1` however it can print 2 rows.  When running with `bar_count=2` I also still get 3 rows sometimes.

This happens for polo and bitfinex.

**Comment by gatapia** [comment]
Can also confirm that backtest `data.current(..., 'volume')` still does not return the 24 hour volume as does live mode.

**Comment by lenak25** [comment]
Thanks @gatapia . We have addressed the issue of empty candles being handled properly (not throwing an exception as you witnessed). 
Regarding the extra candle you get sometimes, thanks for the reminder, we will address it also.
Regarding the 24-volume being returned in backtest as in live, I still owe you an answer (from issue #230), checking it also.

**Comment by lenak25** [comment]
@gatapia, adding a reference to the separate threads you have opened for your two latest observations (#260 , #259 )
Thanks for working to improve the software!

**Comment by lenak25** [comment]
The original issue was fixed at 0.5.4.
