### ISSUE TITLE
`notenoughcasherror` when an open order is filled minutes later

### ISSUE THREAD

**Issue by dmbrady01** [enigmampc/catalyst#237]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: MacOS High Sierra
* Python Version: 2.7.13
* Python Bitness: 64
* How did you install Catalyst: conda
* Python packages: 

_nb_ext_conf              0.4.0                    py27_1
alembic                   0.9.7                     <pip>
anaconda-client           1.6.6            py27hfc9fcca_0
appnope                   0.1.0            py27hb466136_0
attrdict                  2.0.0                     <pip>
backports                 1.0              py27hb4f9756_1
backports.functools_lru_cache 1.4              py27h2aca819_1
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2
backports_abc             0.5              py27h6972548_0
bcolz                     0.12.1                    <pip>
bleach                    2.1.1            py27h2415e5d_0
bleach                    2.1.2                     <pip>
boto3                     1.5.25                    <pip>
botocore                  1.8.39                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0
ccxt                      1.10.1059                 <pip>
certifi                   2018.1.18                py27_0
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
clyent                    1.2.2            py27hc0ae608_0
configparser              3.5.0            py27hc7edf1b_0
contextlib2               0.5.5                     <pip>
cycler                    0.10.0           py27hfc73c78_0
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
cytoolz                   0.9.0                     <pip>
decorator                 4.1.2            py27h9f877ea_0
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.2                     <pip>
entrypoints               0.2.3            py27hd680fb1_2
enum34                    1.1.6            py27hf475452_1
eth-abi                   1.0.0b0                   <pip>
eth-account               0.1.0a2                   <pip>
eth-keyfile               0.5.0                     <pip>
eth-keys                  0.2.0b1                   <pip>
eth-rlp                   0.1.0a2                   <pip>
eth-utils                 1.0.0b1                   <pip>
freetype                  2.8                  h12048fb_1
functools32               3.2.3.2          py27h8ceab06_1
futures                   3.2.0                     <pip>
hexbytes                  0.1.0b0                   <pip>
html5lib                  1.0.1            py27h5233db4_0
idna                      2.6                       <pip>
intel-openmp              2018.0.0             h8158457_8
intervaltree              2.1.0                     <pip>
ipykernel                 4.7.0            py27h5233db4_0
ipython                   5.4.1            py27h2b3d779_1
ipython                   5.5.0                     <pip>
ipython_genutils          0.2.0            py27h8b9a179_0
ipywidgets                7.0.5            py27h8e0d2ca_0
jinja2                    2.10             py27h70b8dc5_0
jmespath                  0.9.3                     <pip>
jsonschema                2.6.0            py27hd9b497e_0
jupyter                   1.0.0                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter_client            5.1.0            py27hfaf569a_0
jupyter_core              4.4.0            py27h5ea6ba4_0
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libgfortran               3.0.1                h93005f0_2
libpng                    1.6.34               he12f830_0
libsodium                 1.0.15               hd9e47c5_0
Logbook                   1.2.1                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.1.1                     <pip>
Mako                      1.0.7                     <pip>
markupsafe                1.0              py27hd3c86fa_1
matplotlib                2.1.2            py27h6d6146d_0
mistune                   0.8.3                     <pip>
mistune                   0.8.1            py27hd7d4354_0
mkl                       2017.0.3                      0
multipledispatch          0.4.9                     <pip>
nb_anacondacloud          1.4.0                    py27_0
nb_conda                  2.2.1            py27h9a0a3a7_0
nb_conda_kernels          2.1.0                    py27_0
nbconvert                 5.3.1            py27h6455e4c_0
nbformat                  4.4.0            py27hddc86d0_0
nbpresent                 3.0.2            py27h73ae17d_1
networkx                  2.1                       <pip>
notebook                  5.2.2            py27h1f6af2b_0
numexpr                   2.6.4                     <pip>
numpy                     1.14.0                    <pip>
numpy                     1.13.1                   py27_0
oauthlib                  2.0.6                     <pip>
openssl                   1.0.2n               hdbc3d79_0
pandas                    0.21.1           py27h1cb45b9_0
pandas                    0.19.2                    <pip>
pandas-datareader         0.6.0                     <pip>
pandoc                    1.19.2.1             ha5e8f32_1
pandocfilters             1.4.2            py27hed78c4e_1
pathlib2                  2.3.0            py27he09da1e_0
patsy                     0.5.0                    py27_0
pexpect                   4.3.1                     <pip>
pexpect                   4.3.0            py27hce281ac_0
pickleshare               0.7.4            py27h37e3d41_0
pip                       9.0.1                    py27_1
prompt_toolkit            1.0.15           py27h4a7b9c2_0
ptyprocess                0.5.2            py27h70f6364_0
pycryptodome              3.4.11                    <pip>
pygments                  2.2.0            py27h1a556bb_0
pyparsing                 2.2.0            py27h5bb6aaf_0
pysha3                    1.0.2                     <pip>
python                    2.7.13                        0
python-dateutil           2.6.1            py27hd56c96b_1
python-editor             1.0.3                     <pip>
pytz                      2017.3           py27h803c07a_0
pyyaml                    3.12             py27ha7932d0_1
pyzmq                     16.0.3           py27h91ccc67_0
qtconsole                 4.3.1                     <pip>
readline                  6.2                           2
redo                      1.6                       <pip>
requests                  2.14.2                   py27_0
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-oauthlib         0.8.0                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.12                    <pip>
scandir                   1.6              py27h97aa1ee_0
scikit-learn              0.19.0              np113py27_0
scipy                     1.0.0                     <pip>
scipy                     0.19.1              np113py27_0
seaborn                   0.8.1            py27h6bd0ddc_0
setuptools                36.4.0                   py27_1
setuptools                38.5.1                    <pip>
simplegeneric             0.8.1            py27h6db5e31_0
singledispatch            3.4.0.3          py27he22c18d_0
six                       1.11.0           py27h7252ba3_1
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.2                     <pip>
sqlite                    3.13.0                        0
ssl_match_hostname        3.5.0.1          py27h8780752_2
statsmodels               0.8.0            py27h6d68dbf_0
subprocess32              3.2.7            py27h24b2887_0
TA-Lib                    0.4.16                    <pip>
tables                    3.4.2                     <pip>
terminado                 0.8.1                     <pip>
terminado                 0.6              py27he40bf16_0
testpath                  0.3.1            py27h72d81a5_0
tk                        8.5.18                        0
toolz                     0.9.0                     <pip>
tornado                   4.5.2            py27h29aec9e_0
traitlets                 4.3.2            py27hcf08151_0
urllib3                   1.22                      <pip>
wcwidth                   0.1.7            py27h817c265_0
web3                      4.0.0b9                   <pip>
webencodings              0.5.1            py27h19a9f58_1
wheel                     0.29.0                   py27_0
widgetsnbextension        3.0.8            py27h418e63b_0
wrapt                     1.10.11                   <pip>
yaml                      0.1.7                hc338f04_2
zeromq                    4.2.2                ha360ad0_2
zlib                      1.2.11               hf3cbc9b_2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
Placed a buy limit order that was open for a few minutes. It executes successfully a few minutes later and my positions/cash are updated accordingly

* What happened instead?
Placed a buy limit order that was open for a few minutes. This set my cash and positions to $0 (since the cash was tied to the pending order). When the order finally executed a few minutes later, a `notenoughcasherror` was thrown. In binance itself, there were no issues and the buy was successful.

...

# Anything else?
My hunch is that there is no state representation for cash being set aside for an open order. While it is technically correct that I did not have cash available to make a new trade, the money that was 'missing' was tied to an order. There should be states for available/total cash, positions, and balances held in orders.
...

**Comment by AvishaiW** [comment]
hi @dmbrady01 i'm trying to reproduce your issue, you are saying that once you place an order, it doesn't consider the money tied to it for the buy? regardless, consider updating catalyst to 0.5.3.

**Comment by dmbrady01** [comment]
Hi @AvishaiW, yes that seems to be what happened. Ok, will update to 0.5.3

**Comment by AvishaiW** [comment]
sorry on the delay, fred just added a fix for this issue. Thanks for noting this out!

**Comment by frisitano** [comment]
Hi @AvishaiW I just cherry picked @fredfortier commit to my local repo and it appears the problem still persists.  I was thinking that maybe the ordering of processes may be an issue for example:

1. order is filled and a transaction is created (open_orders is now empty)
2. catalyst portfolio cash balance is compared with exchange (processed as open_orders is empty)
3. transaction is processed and local portfolio stats are updates

Due to the fact that the portfolio cash is checked before the transaction is processed an error is thrown.

In order to avoid this I'm guessing we'd have to have the processes occur in the following order: 

1. order is filled and a transaction is created (open_orders is now empty)
2. transaction is processed and local portfolio stats are updates
3. catalyst portfolio cash balance is compared with exchange (processed as open_orders is empty).

A possible implementation could be to only check cash balance once both open_orders and transactions are empty.

**Comment by fredfortier** [comment]
Thanks for the breakdown. We’ll revisit this today.

**Comment by frisitano** [comment]
Okay thanks @fredfortier, do you have an approx ETA for the patch?  Do you know if market orders are operating correctly?  I may migrate to market orders, provided they are operating smoothly, whilst you work on a patch for limit orders if the patch is going to take a while to develop.

**Comment by AvishaiW** [comment]
Hi @frisitano, I just pushed in the changes.. please let us know if it's working okay now.. Thanks!

**Comment by frisitano** [comment]
Hi @AvishaiW I had already fetched that commit from @fredfortier exchange modification branch last night and can confirm that it does not fix the problem.  I believe fred is aware that the commit does not rectify the issue as above he says he'll revisit it today.

**Comment by fredfortier** [comment]
ETA - this afternoon or evening (PST).

**Comment by fredfortier** [comment]
@AvishaiW and I reviewed your notes. He made some changes which he is
currently testing. He will pick this up in the morning his time which is
only a few hours away.

**Comment by AvishaiW** [comment]
Hi, I was able to reproduce this issue, working now on a solution..

**Comment by AvishaiW** [comment]
Hi, I added the changes on the develop branch.. Thanks and sorry on the delay!

**Comment by frisitano** [comment]
@AvishaiW Thank you very much for addressing this in a timely manor.  I'll pull from the develop branch and let you know how things go.

**Comment by AvishaiW** [comment]
added on catalyst 0.5.4
